#!/bin/bash

set -eu -o pipefail

MODULE_REACT_DIR='web/modules/custom/ca_custom_block_react_timer/src/frontend'

cd $MODULE_REACT_DIR || exit

npm run test

echo "React block timer FE tests complete."
